### ISSUE TITLE
只发心跳包，一段时间就掉线问题

### ISSUE THREAD

**Issue by lgjx123** [liuxq/StriveGame#2]
放着什么都不做，一段时间之后就会在MessageReader.process这里面的
reader.msgid = reader.stream:readUint16()
报错，读出来一个不存在的message id 0。经查问题出在

elseif(msg.msglen == 0) then
					-- 如果是0个参数的消息，那么没有后续内容可读了，处理本条消息并且直接跳到下一条消息
					msg:handleMessage(stream);
					state = KBEngineLua.READ_STATE_MSGID;
					expectSize = 2;

这里，
state,expectSize应该改为

reader.state = KBEngineLua.READ_STATE_MSGID;
reader.expectSize = 2;

**Comment by kbengine** [comment]
嗯，kbe插件这块也是后面加了心跳支持才加的代码，可以看看messagereader

**Comment by liuxq** [comment]
感谢lgjx123 ，已修改~
