### ISSUE TITLE
新版本插件一些改变

### ISSUE THREAD

**Issue by kbengine** [liuxq/StriveGame#4]
纠正错别字（ReLogin, DisableConnect, ConnectStatus ）=> （relogin， disconnect… … 
…ed， connectionState）
https://github.com/kbengine/kbengine_unity3d_demo/commit/edd1ec0994865bc5a69abf1aa3ac048651a6f284

**Comment by kbengine** [comment]
Vector传输优化， 不需要记录size
https://github.com/kbengine/kbengine/issues/430

https://github.com/kbengine/kbengine_unity3d_plugins/commit/a67aeecc4703dee4ffd5601c4096eb5787829def

**Comment by liuxq** [comment]
已修改
